entropydata.client.host=https://api.entropy-data.com
entropydata.client.apikey=your-api-key

entropydata.client.databricks.workspace.host=https://dbc-xxxxxx.cloud.databricks.com
entropydata.client.databricks.workspace.client-id=your-workspace-service-principal-client-id
entropydata.client.databricks.workspace.client-secret=your-workspace-service-principal-client-secret

entropydata.client.databricks.account.host=https://accounts.cloud.databricks.com
entropydata.client.databricks.account.account-id=your-account-id
entropydata.client.databricks.account.client-id=your-account-service-principal-client-id
entropydata.client.databricks.account.client-secret=your-account-service-principal-client-secret

entropydata.client.databricks.accessmanagement.connectorid=databricks-access-management
entropydata.client.databricks.accessmanagement.enabled=true

entropydata.client.databricks.assets.connectorid=databricks-assets
entropydata.client.databricks.assets.enabled=true
entropydata.client.databricks.assets.pollinterval=PT10M
entropydata.client.databricks.assets.tables.include=*
